repositories:
- name: ghcr
  url: ghcr.io
  oci: true

kubeVersion: v1.34

releases:
- name: kagent
  chart: ghcr/kagent-dev/kagent/helm/kagent
  version: 0.7.4
  namespace: kagent
  values:
  - kagent-values.yaml
