apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- rendered/rendered-all.yaml
- kagent-ui-ingress.yaml
- mcp
- agents

secretGenerator:
- name: kagent-secrets
  envs:
  - .env
  namespace: kagent
  options:
    disableNameSuffixHash: true
