apiVersion: kagent.dev/v1alpha1
kind: MCPServer
metadata:
  name: brave-server
  namespace: kagent
spec:
  deployment:
    args:
    - "-y"
    - "@brave/brave-search-mcp-server"
    cmd: npx
    secretRefs:
      - name: mcp-secrets
    image: node:24-alpine3.21
    port: 3000
  stdioTransport: {}
  transportType: stdio
