apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- brave-search-mcp.yaml
- gh-remote-mcp.yaml
- context7-remote.yaml

secretGenerator:
- name: mcp-secrets
  envs:
  - .env
  namespace: kagent
  options:
    disableNameSuffixHash: true
